#' Visual Studio Project Build Definition Information
#'
#' @description
#' These functions will allow you to scrape build definition information from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param project the name of the project in \code{domain} to look at
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#' @param query a list of extra parameters that can be sent to the API call:
#' \describe{
#' \item{to_complete}{to_complete}
#' }
#'
#' @rdname vsts_build_def
#' @export
vsts_get_build_defs <- function(domain, project, auth_key, query = NULL) {
  uri <- paste0('https://', domain, '.visualstudio.com/', project, '/_apis/build/builds?api-version=4.1-preview')

  response <- httr::GET(uri, httr::add_headers(Authorization = auth_key), query = query)
  if(response$status_code != 200) {
    cat('Unable to perform request, status code:', response$status_code, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(.) %>% .$value
  return(invisible(content))
}
