#' Visual Studio Projects
#'
#' @description
#' These functions will allow you to scrape project information from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#' @param quiet logical whether want general running information from printing. Any issue with the API call will
#' still show up if set to \code{TRUE}
#'
#' @rdname vsts_project
#' @export
vsts_get_projects <- function(domain, auth_key, quiet = FALSE) {
  uri <- paste0('https://', domain, '.visualstudio.com/DefaultCollection/_apis/projects?api-version=1.0')

  response <- httr::GET(uri, httr::add_headers(Authorization = auth_key))
  if(response$status_code != 200) {
    cat('Unable to perform request, status code:', response$status_code, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(.) %>% .$value
  if(!quiet) cat('Available projects:', paste(content$name, collapse = ', '), '\n')
  return(invisible(content))
}
