#' Visual Studio Project Release Definition Information
#'
#' @description
#' These functions will allow you to scrape release definition information from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param project the name of the project in \code{domain} to look at
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#' @param quiet logical whether want general running information from printing. Any issue with the API call will
#' still show up if set to \code{TRUE}
#'
#' @rdname vsts_release_def
#' @export
vsts_get_release_defs <- function(domain, project, auth_key, quiet = FALSE) {
  uri <- paste0('https://', domain, '.vsrm.visualstudio.com/', project, '/_apis/release/definitions')

  response <- httr::GET(uri, httr::add_headers(Authorization = auth_key))
  if(response$status_code != 200) {
    cat('Unable to perform request, status code:', response$status_code, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(.) %>% .$value
  if(!quiet) cat('Available release definitions:', paste(content$name, collapse = ', '), '\n')
  return(invisible(content))
}

#' Visual Studio Project Release Information
#'
#' @description
#' These functions will allow you to scrape releases information from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param project the name of the project in \code{domain} to look at
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#' @param body a list of extra parameters that can need to be sent to the API call (* mandatory):
#' \describe{
#' \item{\code{artifacts *}}{[character] the name of a branch in the repository (cannot combine with \code{commit})}
#' \item{\code{definitionId *}}{[integer] the id of a commit in the repository (cannot combine with \code{branch})}
#' \item{\code{description *}}{[character] path of an item in the repository}
#' \item{\code{isDraft}}{[character] name of the person who committed the change}
#' \item{\code{manualEnvironments}}{[character] name of the author}
#' \item{\code{properties}}{[Date] start date to search from}
#' \item{\code{reason}}{[Date] end date to search from}
#' }
#'
#' @rdname vsts_release
#' @export
vsts_create_release <- function(domain, project, auth_key, body) {
  uri <- paste0('https://', domain, '.vsrm.visualstudio.com/', project, '/_apis/release/releases?api-version=4.1-preview.6')

  content_body <- jsonlite::toJSON(body, auto_unbox = TRUE)

  response <- httr::POST(uri, httr::add_headers(Authorization = auth_key), httr::content_type('application/json'), body = content_body)
  if(httr::status_code(response) != 200) {
    cat(httr::http_condition(response, 'message', paste0('Create release definition #', body$definitionId))$message, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(.)
  return(invisible(content))
}

#' Visual Studio Project Release Information
#'
#' @description
#' These functions will allow you to scrape release information from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param project the name of the project in \code{domain} to look at
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#' @param query a list of extra parameters that can be sent to the API call:
#' \describe{
#' \item{\code{definitionId}}{[integer] Releases from this release definition Id.}
#' }
#'
#' @rdname vsts_get_release
#' @export
vsts_get_releases <- function(domain, project, auth_key, query = NULL) {
  uri <- paste0('https://', domain, '.vsrm.visualstudio.com/', project, '/_apis/release/releases?api-version=4.1-preview.6')

  response <- httr::GET(uri, httr::add_headers(Authorization = auth_key), query = query)
  if(httr::status_code(response) != 200) {
    cat(httr::http_condition(response, 'message', 'Get release definitions')$message, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(., flatten = TRUE) %>% .$value
  return(invisible(content))
}

#' @param release ID number of the release to look at
#'
#' @rdname vsts_release
#' @export
vsts_get_release <- function(domain, project, release, auth_key) {
  uri <- paste0('https://', domain, '.vsrm.visualstudio.com/', project, '/_apis/release/releases/', release,
                '?api-version=4.1-preview.6')

  response <- httr::GET(uri, httr::add_headers(Authorization = auth_key), httr::content_type('application/json'))
  if(httr::status_code(response) != 200) {
    cat(httr::http_condition(response, 'message', 'Get release definitions')$message, '\n')
    return(invisible(NULL))
  }

  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(.)
  return(invisible(content))
}

#' Visual Studio Project Release Environment Information
#'
#' @description
#' These functions will allow you to run release environment tasks from Visual Studio.
#'
#' @param domain the location of the visual studio server
#' @param project the name of the project in \code{domain} to look at
#' @param release the release ID of the release
#' @param env the release environment ID to release on
#' @param auth_key authentication key generated by using \code{\link{vsts_auth_key}}
#'
#' @rdname vsts_release_env
#' @export
vsts_deploy_release <- function(domain, project, release, env, auth_key) {
  uri <- paste0('https://', domain, '.vsrm.visualstudio.com/', project, '/_apis/Release/releases/', release,
                '/environments/', env, '?api-version=4.1-preview.5')

  content_body <- jsonlite::toJSON(list(status = 'inProgress'), auto_unbox = TRUE)

  response <- httr::PATCH(uri, httr::add_headers(Authorization = auth_key), httr::content_type('application/json'), body = content_body)
  if(httr::status_code(response) != 200) {
    cat(httr::http_condition(response, 'message', httr::content(response)$message)$message, '\n')
    return(invisible(NULL))
  }

  cat('Deployment of release has started.\n')
  content <- httr::content(response, as = 'text', encoding = 'UTF-8') %>% jsonlite::fromJSON(., flatten = TRUE)
  return(invisible(content))
}
